# --- Builder ---
FROM node:20-alpine AS builder
WORKDIR /app

COPY . .
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm nx build posts-service

# --- Runner ---
FROM node:20-alpine
WORKDIR /app

RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY --from=builder /app/dist/apps/posts-service ./dist
COPY --from=builder /app/prisma ./prisma

CMD pnpm prisma migrate deploy && node dist/main.js
