# --- Builder ---
FROM node:20-alpine AS builder

WORKDIR /app

COPY . .
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile
RUN pnpm nx build files-service

# --- Runner ---
FROM node:20-alpine
WORKDIR /app

RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --frozen-lockfile

COPY --from=builder /app/dist/apps/files-service ./dist

CMD ["node", "dist/main.js"]
